### ISSUE TITLE
3_nedelja

### ISSUE THREAD

**Issue by gianthead97** [MATF-Computer-Networks/RM-4I-2019-2020#1]
[Ovde](https://github.com/MATF-Computer-Networks/RM-4I-2019-2020/blob/master/RM4I_2019_2020/p03_InetAddress/p03_network_interfaces/NetworkInterfaces.java)

33.linija, metod networkInterfaces() ne postoji.

**Comment by ivan-ristovic** [comment]
Koja verzija Jave je kod Vas? Ovaj metod je dodat u verziji 8 iirc (zajedno sa Stream<T> kao klasom za implementaciju kolekcijskih stream-ova).

**Comment by gianthead97** [comment]
Apdejtovao sam na Java13, sad radi.
Hvala.

Hvala i na dodatnom infou,
